image: python:3.11.2
pipelines:
  default:
    - step:
        script:
          - echo "hello world!"
  branches:
    crm-accounting-frontend:
      - step:  
          script:
            - ssh ubuntu@16.24.36.173 /home/ubuntu/Erisbiz/eris-biz-frontend/devCdScript.sh 
