import moment from 'moment';

/* eslint-disable import/prefer-default-export */
export const purchaseInvoiceInitialValue = {
  date: moment().format('YYYY-MM-DD'),
  location: '',
  supplier_id: '',
  refrence_number: '',
  attachment: '',
  pur_order_items: [
    {
      item: '',
      quantity: 0,
      price: 0,
      total: 0,
      discount: 0,
      vat: 0,
      net_amount: 0,
    },
  ],
  requestor_signature_show: true,
  show_stamp: true,

  pur_order_suffix: 'LPO',
  customer_type_suffix: '',
  currency: 'AED',
  currency_symbol: 'AED',
  currency_id: null,
  convert_to_aed: true,
  exchange_rate: 1,
  pur_order_date: moment().format('YYYY-MM-DD'),
  event: '',
  tax_treatment: '',
  trn: '',
  place_of_supply: '',
  requestor_name: '',
  period_start: '',
  period_end: '',
  notes: '',
  account_num: '',
  iban: '',
  advance_pyments: '',
  payment_notes: '',
  discount: 0,
  amount_total: 0,
  amount_total_aed: 0,
  vat_total: 0,
  vat_total_aed: 0,
  grand_total: 0,
  grand_total_aed: 0,
  sub_total: 0,
  address: '',
  city: '',
  state: '',
  zipcode: '',
  country: '',
};
