export const itemsInitialValues = {
  item_name: '',
  sku_hs_code: '',
  sale_price: '',
  cost_price: '',
  item_type: 'Goods',
  is_active: true,
  account_no: '',
  bar_code: '',
  unit: 'kg',
  recorder: '',
  description: '',
  item_image: '',
  part_number: '',
  supplier: '',
  brand: '',
  category: '',

  current_value: 0.0,
  sale_account: '1',
  cost_account: '1',
  inventory_coa: '',
  sale_account_label: 'Cash in Bank -  MCB',
  cost_account_label: 'Cash in Bank -  MCB',
  inventory_coa_label: 'Cash in Bank -  MCB',
  is_digital_service: false,
  item_sale_amount_prefix: 'AED',
  sale_description: null,
  item_cost_amount_prefix: 'AED',
  cost_description: null,
  is_tracking_inventory: false,
  opening_stock: 0,
  opening_stock_per_unit: 0.0,
  dynamic_opening_stock: 0.0,
  dynamic_opening_stock_per_unit: 0.0,
  is_item_used: false,
};

export const test = '';
