import moment from 'moment';
import { DATE_FORMATE_ADD, NEW_PURCHASE_ITEM_OBJECT } from 'utilities/constants';

export const purchaseInvoiceStatusList = [
  { label: 'All', value: '' },
  { label: 'Draft', value: 'draft' },
  { label: 'Due', value: 'due' },
  { label: 'Over Due', value: 'over due' },
  { label: 'Void', value: 'void' },
  { label: 'Partially Paid', value: 'partially paid' },
  { label: 'Paid', value: 'paid' },
];
export const purchaseInvoiceInitialValue = {
  invoice_date: moment().format(DATE_FORMATE_ADD),
  pur_order_id: '',
  location: '',
  supplier_invoice_num: '',
  supplier_id: '',
  refrence_number: '',
  bill_docs: [],
  bill_items: [NEW_PURCHASE_ITEM_OBJECT],
  requestor_signature_show: true,
  show_stamp: true,
  credit_account: '',
  pur_order_suffix: 'PO',
  customer_type_suffix: '',
  currency: 'AED',
  currency_symbol: 'AED',
  currency_id: null,
  convert_to_aed: true,
  exchange_rate: 1,
  event: '',
  tax_treatment: '',
  trn: '',
  place_of_supply: '',
  requestor_name: '',
  period_start: '',
  period_end: '',
  notes: '',
  account_num: '',
  iban: '',
  advance_pyments: '',
  payment_notes: '',
  discount: 0,
  amount_total: 0,
  amount_total_aed: 0,
  vat_total: 0,
  vat_total_aed: 0,
  payment_terms: 'Net 0',
  grand_total: 0,
  grand_total_aed: 0,
  sub_total: 0,
  address: '',
  city: '',
  state: '',
  zipcode: '',
  country: '',
};

export const purchaseInvoiceFiltersOptionsList = [
  {
    name: 'date',
    date: true,
    fullWidth: true,
    placeholder: 'Date',
  },
  {
    name: 'supplier_name',
    // fullWidth: true,
    placeholder: 'Supplier Name',
  },
  {
    name: 'bill_num',
    // fullWidth: true,
    placeholder: 'invoice Number',
  },
  {
    name: 'reference',
    // fullWidth: true,
    placeholder: 'Reference#',
  },
  {
    name: 'status',
    // fullWidth: true,
    placeholder: 'Status',
    options: purchaseInvoiceStatusList,
  },
  {
    name: 'without_change_grand_total',
    fullWidth: true,
    placeholder: 'Amount',
    type: 'number',
  },
];
