import formatAmount from 'utilities/formatAmount';

export const customersHeadCell = [
  {
    id: 'customer_name',
    numeric: true,
    disablePadding: false,
    label: 'Customer',
    align: 'left',
    isLink: true,
  },
  {
    id: 'email',
    numeric: true,
    disablePadding: false,
    label: 'Email',
    align: 'left',
  },
  {
    id: 'contact_person',
    numeric: true,
    disablePadding: false,
    label: 'Contact Person',
    align: 'left',
  },
  {
    id: 'contact',
    numeric: true,
    disablePadding: false,
    label: 'Contact',
    align: 'left',
  },
  {
    id: 'vat_reg_no',
    numeric: true,
    disablePadding: false,
    label: 'VAT Registration',
    align: 'left',
  },
  {
    id: 'invoice_city',
    numeric: true,
    disablePadding: false,
    label: 'City',
    align: 'left',
  },
  {
    id: 'invoice_country',
    numeric: true,
    disablePadding: false,
    label: 'Country',
    align: 'left',
  },
];
export const customerContactHeadCells = [
  {
    id: 'name',
    numeric: false,
    disablePadding: true,
    label: 'Name',
    align: 'left',
  },
  {
    id: 'designation',
    numeric: true,
    disablePadding: false,
    label: 'Designation',
    align: 'left',
  },
  {
    id: 'email',
    numeric: true,
    disablePadding: false,
    label: 'Email',
    align: 'left',
  },

  {
    id: 'mobile_num',
    numeric: true,
    disablePadding: false,
    label: 'Mobile Number',
    align: 'left',
  },

  {
    id: 'notes',
    numeric: true,
    disablePadding: false,
    label: 'Remarks',
    align: 'left',
  },
];

export const customerQuotationsHeadCells = [
  {
    id: 'date',
    numeric: true,
    disablePadding: false,
    label: 'Date',
    align: 'left',
    date: true,
  },
  {
    id: 'quotation_formatted_number',
    numeric: true,
    disablePadding: false,
    label: 'Quotation #',
    align: 'left',
    isLink: true,
    handleLink: row => `/pages/accounting/sales/quotations/${row.uuid}/detail`,
  },
  {
    id: 'grand_total',
    numeric: true,
    disablePadding: false,
    label: 'Amount',
    align: 'left',
    cellValueAction: value => formatAmount(value),
  },
  {
    id: 'status',
    numeric: true,
    disablePadding: false,
    label: 'Status',
    align: 'left',
  },
];
export const customerSalesInvoiceHeadCells = [
  {
    id: 'date',
    numeric: true,
    disablePadding: false,
    label: 'Date',
    align: 'left',
    date: true,
  },
  {
    id: 'invoice_formatted_number',
    numeric: true,
    disablePadding: false,
    label: 'Invoice #',
    align: 'left',
    isLink: true,
    handleLink: row => `/pages/accounting/sales/sale-invoice/${row.id}/detail`,
  },
  {
    id: 'grand_total',
    numeric: true,
    disablePadding: false,
    label: 'Amount',
    align: 'left',
    cellValueAction: value => formatAmount(value),
  },
  {
    id: 'amount_due',
    numeric: true,
    disablePadding: false,
    label: 'Balance Due',
    align: 'left',
    cellValueAction: value => formatAmount(value),
  },
  {
    id: 'status',
    numeric: true,
    disablePadding: false,
    label: 'Status',
    align: 'left',
  },
];
export const customerReceiptVoucherInvoiceHeadCells = [
  {
    id: 'payment_date',
    numeric: true,
    disablePadding: false,
    label: 'Date',
    align: 'left',
    date: true,
  },
  {
    id: 'payment_num',
    numeric: true,
    disablePadding: false,
    label: 'Payment #',
    align: 'left',
    isLink: true,
    handleLink: row => `/pages/accounting/sales/receipt-voucher/${row.id}/detail`,
  },
  {
    id: 'reference_num',
    numeric: true,
    disablePadding: false,
    label: 'Reference #',
    align: 'left',
    cellValueAction: value => formatAmount(value),
  },
  {
    id: 'payment_mode',
    numeric: true,
    disablePadding: false,
    label: 'Payment Mode',
    align: 'left',
  },
  {
    id: 'total',
    numeric: true,
    disablePadding: false,
    label: 'Amount',
    align: 'left',
    cellValueAction: value => formatAmount(value),
  },
  {
    id: 'unused_amount',
    numeric: true,
    disablePadding: false,
    label: 'Unused Amount',
    align: 'left',
    cellValueAction: value => formatAmount(value),
  },
  {
    id: 'status',
    numeric: true,
    disablePadding: false,
    label: 'Status',
    align: 'left',
  },
];
export const customerCreditNoteInvoiceHeadCells = [
  {
    id: 'credit_note_date',
    numeric: true,
    disablePadding: false,
    label: 'Date',
    align: 'left',
    date: true,
  },
  {
    id: 'credit_note_formatted_number',
    numeric: true,
    disablePadding: false,
    label: 'Credit Note #',
    align: 'left',
    isLink: true,
    handleLink: row => `/pages/accounting/sales/credit-notes/${row.id}/detail`,
  },
  {
    id: 'reference_num',
    numeric: true,
    disablePadding: false,
    label: 'Reference #',
    align: 'left',
    cellValueAction: value => formatAmount(value),
  },
  {
    id: 'credits_remaining',
    numeric: true,
    disablePadding: false,
    label: 'Balance',
    align: 'left',
    cellValueAction: value => formatAmount(value),
  },
  {
    id: 'grand_total',
    numeric: true,
    disablePadding: false,
    label: 'Amount',
    align: 'left',
    cellValueAction: value => formatAmount(value),
  },

  {
    id: 'status',
    numeric: true,
    disablePadding: false,
    label: 'Status',
    align: 'left',
  },
];
export const customerJournalsHeadCells = [
  {
    id: 'created_at',
    numeric: true,
    disablePadding: false,
    label: 'Date',
    align: 'left',
    date: true,
  },
  {
    id: 'account_name',
    numeric: true,
    disablePadding: false,
    label: 'Credit Note #',
    align: 'left',
  },
  {
    id: 'debit',
    numeric: true,
    disablePadding: false,
    label: 'Balance',
    align: 'left',
    cellValueAction: value => formatAmount(value),
  },
  {
    id: 'credit',
    numeric: true,
    disablePadding: false,
    label: 'Reference #',
    align: 'left',
    cellValueAction: value => formatAmount(value),
  },
];
